# Generated by Django 3.2.13 on 2022-10-14 13:10

import common.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
