# Generated by Django 3.2.13 on 2022-10-14 13:35

import common.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.managers.CustomUserManager()),
            ],
        ),
    ]
