# Generated by Django 3.2.13 on 2022-09-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='application.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='common.organization'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='owning_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_events', to='application.application'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='originating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.applicantinformation'),
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='common.organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationitemone',
            name='co_applicants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_ones', to='application.applicantinformation'),
        ),
        migrations.AddField(
            model_name='application',
            name='item_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.applicationitemone'),
        ),
        migrations.AddField(
            model_name='application',
            name='item_two',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.applicationitemtwo'),
        ),
    ]
