# Generated by Django 3.2.13 on 2022-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='address_line_one',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinformation',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
